version: '3.8'

services:
  mongo-primary:
    image: mongo
    container_name: mongo-primary
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
      REPLICASET: rs0
    command: mongod --replSet rs0 --bind_ip_all --keyFile /opt/mongo/mongo-keyfile
    volumes:
      - ./mongo-keyfile:/opt/mongo/mongo-keyfile

  mongo-secondary:
    image: mongo
    container_name: mongo-secondary
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
      REPLICASET: rs0
    command: mongod --replSet rs0 --bind_ip_all --keyFile /opt/mongo/mongo-keyfile
    depends_on:
      - mongo-primary
    volumes:
      - ./mongo-keyfile:/opt/mongo/mongo-keyfile

  mongo-arbiter:
    image: mongo
    container_name: mongo-arbiter
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
      REPLICASET: rs0
    command: mongod --replSet rs0 --bind_ip_all --keyFile /opt/mongo/mongo-keyfile
    depends_on:
      - mongo-primary
    volumes:
      - ./mongo-keyfile:/opt/mongo/mongo-keyfile
