version: '3.4'
services:
  pg-0:
    image: debezium/postgres:16
    ports:
      - "5432:5432"
    volumes:
      - "pg_0_data:/bitnami/postgresql"
      - "./conf.d/:/bitnami/postgresql/conf/conf.d/"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "meroxadb", "-U", "meroxauser" ]
      timeout: 30s
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_USER=meroxauser
      - POSTGRES_PASSWORD=meroxapass
      - POSTGRES_DB=meroxadb
volumes:
  pg_0_data:
    driver: local
