version: "3.7"
services:
  elasticsearch-8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: elasticsearch-8
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
  kibana-8:
    container_name: kibana-8
    image: docker.elastic.co/kibana/kibana:8.4.2
    restart: always
    environment:
      - XPACK_SECURITY_ENABLED=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch-8:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-8
