services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: conduit_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus_config:/etc/prometheus
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    ports:
      - 9090:9090
    extra_hosts:
      host.docker.internal: host-gateway

  grafana:
    image: grafana/grafana:11.2.0
    container_name: conduit_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASS
      - GF_USERS_ALLOW_SIGN_UP=false
    expose:
      - 3000
    ports:
      - 9091:3000

volumes:
  grafana-storage:
  prometheus-storage:
