version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: conduit_prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    ports:
      - 9090:9090
    extra_hosts:
      host.docker.internal: host-gateway

  grafana:
    image: grafana/grafana:latest
    container_name: conduit_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASS
      - GF_USERS_ALLOW_SIGN_UP=false
    expose:
      - 3000
    ports:
      - 9091:3000
